### ISSUE TITLE
einige Tippfehler in /fullcalendar/dca/tl_fullcalendar.php ab Zeile 36

### ISSUE THREAD

**Issue by KlausGrenoble** [kozi/contao-fullcalendar#1]
Dort bitte die Klammer im array ) entfernen und dann die fehlenden Kommata im DCA ergänzen.
theobald
https://community.contao.org/de/showthread.php?58210-martin-kozianka-contao-fullcalendar-0-5-0

**Comment by kozi** [comment]
Erledigt. Danke für den Hinweis! Neue Version **0.5.2**
