### ISSUE TITLE
Kompatibilität für Contao 4

### ISSUE THREAD

**Issue by Jaaaan** [kozi/contao-fullcalendar#10]
Im neuen Contao Manager wird die Erweiterung bereits im Katalog angzeigt, jedoch schlägt eine Installation aufgrund fehlender Freigabe für Contao 4 immer fehl.
Wäre es möglich, diese Freigabe für Contao 4 zu erteilen?

Infos zu den nötigen Anpassungen: https://github.com/contao-community-alliance/composer-plugin/blob/master/README.md

**Comment by kozi** [comment]
Guck ich mir an und werde das sicher in den nächsten Wochen mal angehen. Solltest du dich damit auskennen kannst du natürlich auch einen Pull Request mit den notwendigen Änderungen erstellen.

**Comment by Jaaaan** [comment]
Da die Erweiterung bereits unter Contao 3.5 läuft, könnte es reichen, in der composer.json die Voraussetzungen anzupassen:
`"contao/core-bundle": "~3.5 || ~4.1"` bzw. `"contao/core-bundle": "~3.5 || ~4.4"`

> Contao 4 was designed to be backwards-compatible with Contao 3. Therefore, it is very much possible to have an extension that does support both Contao 3 and Contao 4. If your extension works with Contao 3.5 and Contao 4, a correct requirement could look like this:
> 
> ```
> {
>     "require": {
>         "contao/core-bundle": "~3.5 || ~4.1"
>     }
> }
> ```

**Comment by Jaaaan** [comment]
Mit dem `dev-master` kann man bereits erfolgreich die Erweiterung über den Contao Manager installieren als auch aktivieren. ;-)

Bei der Einbindung des Fullcalenders erscheint bei mir im Frontend jedoch folgende Fehlermeldung:
`Warning: strip_tags() expects parameter 1 to be string, object given in /www/htdocs/vendor/martin-kozianka/contao-fullcalendar/src/ContaoFullcalendar/EventMapper.php on line 47`

**Comment by kozi** [comment]
> Bei der Einbindung des Fullcalenders erscheint bei mir im Frontend jedoch folgende Fehlermeldung:
Warning: strip_tags() expects parameter 1 to be string, object given in /www/htdocs/vendor/martin-kozianka/contao-fullcalendar/src/ContaoFullcalendar/EventMapper.php on line 47

Wann ergibt sich dieses Problem?

**Comment by Jaaaan** [comment]
Ich hatte das Modul "Fullcalendar" in einen Artikel eingebunden, konnte es jedoch nach Neuinstallation der Erweiterung nicht mehr reproduzieren.

Im Zusammenhang bekomme ich folgende Fehlermeldung im Head-Bereich der Seite, auch in einem frisch aufgesetzten Contao, aber erst nach Installation der Erweiterung:
`Warning: filemtime(): stat failed for /www/htdocs/assets/jquery/js/jquery.min.js in /www/htdocs/vendor/contao/core-bundle/src/Resources/contao/library/Contao/Controller.php on line 854`
Auch nach Deinstallation des Packages bleibt diese Fehlermeldung weiter vorhanden, ich habe deshalb die Vermutung, dass die Fehlerquelle in einer der Abhängigkeitserweiterungen von "Fullcalendar" steckt bzw. kann nicht genau deren Fehlerquelle identifizieren.
Bei einer Deinstallation werden diese Abhängigkeitserweiterungen nicht mit entfernt:
`Package operations: 0 installs, 0 updates, 1 removal - Removing martin-kozianka/contao-fullcalendar (dev-master 0cbb25a)`

Der richtige Pfad für's jQuery wäre unter Contao 4 `/assets/jquery/jquery.min.js`.

**Comment by kozi** [comment]
Bitte einmal mit dem aktuellen Release 0.9.1 testen und mir auch alle Eckdaten des Systems (OS, Contao-Version, andere Erweiterungen?!) schicken, danke!

**Comment by kozi** [comment]
`/assets/jquery/js/jquery.min.js` sollte auch vorhanden sein. Die Datei wird schon initial von Contao installiert. Ist jQuery Version **v1.12.4**.
Die Dateien direkt in `/assets/jquery/` werden durch die fullcalender-Abhängigkeiten installiert. Das passiert über das *Modul* `robloach/component-installer`

**Comment by Jaaaan** [comment]
Ich habe mal in allen Contao 4 Umgebungen bei mir nachgeschaut, die mit dem CM installiert worden sind.
In der heute installierten Version, wo ich nur deine Erweiterung habe (diesmal mit neustem Release installiert), ist der Ordner `js` tatsächlich vorhanden und keine Fehlermeldung im Frontend, in den anderen Installationen nicht.
Die Umgebungen liegen bei All Inkl in verschiedenen Tarifen mit PHP 7, die fehlerhaften Umgebungen wurden zum Teil (Inhalt und Theme) aus Contao 3.5 übernommen.
Ich vermute eher, es handelt sich bei mir in der Installation/Theme um einen Fehler, dem werde ich in den kommenden Tagen mal nachgehen.
Danke auch für die Hintergrundinfos!

**Comment by kozi** [comment]
Sollte ab Version ```1.1.1``` jetzt in Contao 4.4 vollständig funktionieren.

**Comment by christianmildner** [comment]
Danke für die Erweiterung!!!! Die Installation verläuft unter 4.4.6 problemlos. Bei mir wird auch der Standardordner /assets/jquery/ ersetzt. Dabei geht der Ordner /assets/jquery/js/ verloren, welcher zur Standardinstallation der 4.4.x gehört. Damit wird bei mir im Theme einiges nicht mehr ausgeführt. Zudem werden im Ordner /assets/ die Dateien require-built.js, require.js, require.css sowie require.config.js angelegt, welche
