### ISSUE TITLE
tl_calender_events spalte source wird nicht befüllt (Google Kalender)

### ISSUE THREAD

**Issue by swinde** [kozi/contao-fullcalendar#12]
Hallo erst einmal möchte ich mich für die Erweiterung bedanken!

Beim Installieren und testen sind mir 2 Probleme aufgefallen!

1. Alle eingelesenen Events (Google Kalender) geben im Eventdetails keine Texte aus. Es wird nur eine ID ausgegeben. Der Grund ist das in der Tabelle tl-calendar_events.php die Spalte source nicht befüllt wird. Ein 'default' bewirkt, daß in den Events das Weiterleitungsziel auf Standard gesetzt wird.

Früher könnte man sich mit einem Eintrag in der dcaconfic.php behelfen, das greift aber scheinbar nicht mehr. 
Folgender Eintrag hatte geholfen:

// tl_calendar_events 'source' mit default ausfüllen, damit der Detailstext angezeigt wird
$GLOBALS['TL_DCA']['tl_calendar_events']['fields']['source'] = array
(
'label'                   => &$GLOBALS['TL_LANG']['tl_calendar_events']['source'],
'default'                 => 'default',
'exclude'                 => true,
'filter'                  => true,
'inputType'               => 'radio',
'options_callback'        => array('tl_calendar_events', 'getSourceOptions'),
'reference'               => &$GLOBALS['TL_LANG']['tl_calendar_events'],
'eval'                    => array('submitOnChange'=>true, 'helpwizard'=>true),
'sql'                     => "varchar(32) NOT NULL default 'default'"
);

Edit: 
Contao Version 4.4.13
Ich habe mich derzeit mit einem Eintrag unter app/Recources/dca/tl_calendar_events.php beholfen.

**Comment by kozi** [comment]
Solved in `2.0.1`
