### ISSUE TITLE
Synchronisieren eines Kalenders im Backend

### ISSUE THREAD

**Issue by swinde** [kozi/contao-fullcalendar#13]
Beim Synchronisieren eines Kalenders im Backend wird man auf die Startseite im Frontend weitergeleitet.

**Comment by kozi** [comment]
Welche Version wird verwendet? Contao-Version und Version der Erweiterung?

**Comment by swinde** [comment]
Es ist die gleiche Installation wie unter #12 
Contao 4 | Erweiterung über Composer installiert 1.1.1

**Comment by rustykowski** [comment]
Dazu noch eine Frage: Muss man beim Synchronisationstyp "Link zu einer ICS-Datei" eigentlich manuell aktualisieren, oder macht das die Erweiterung regelmäßig automatisch?

**Comment by Acta2000** [comment]
> 
> 
> Dazu noch eine Frage: Muss man beim Synchronisationstyp "Link zu einer ICS-Datei" eigentlich manuell aktualisieren, oder macht das die Erweiterung regelmäßig automatisch?

Gibt es für diese Frage schon eine Lösung. Zum einen wird bei mir auch die Startseite geladen zum anderen stell ich mir auch die Frage wie man den Import automatisieren kann.

**Comment by kozi** [comment]
```
$GLOBALS['TL_CRON']['hourly'][]                         = ['\ContaoFullcalendar\CalendarSync', 'syncCal'];
```
Der Import ist eine *einseitige Synchronisation*. Der Kalender wird **stündlich** aktualisiert.
