### ISSUE TITLE
Farbauswahl mit colorpicker

### ISSUE THREAD

**Issue by swinde** [kozi/contao-fullcalendar#14]
der Colorpicker bei der Farbauswahl für den Google Kalender funktioniert nicht.
Das Plugin ist allerding aktiv und funktioniert im internen CSS Editor einwandfrei.

**Comment by kozi** [comment]
Welche Version wird verwendet? Contao-Version und Version der Erweiterung?

**Comment by swinde** [comment]
Es ist die gleiche Installation wie unter #12 
Contao 4 | Erweiterung über Composer installiert 1.1.1

**Comment by BennyK80** [comment]
Das Feld "Synchronisationstyp" überlagert "Kalenderalias" und "Farbe".
Eine Änderung der CSS-Klasse von "long" auf "clr" würde das Problem beheben.

**Comment by rustykowski** [comment]
BennyK80s Hinweis kann ich bestätigen

**Comment by kozi** [comment]
Ist repariert. Danke für den Hinweis! **Version:** `2.0.2`
