### ISSUE TITLE
Installation auf Contao 3.5.28 manuell – Kalender wird nicht angezeigt

### ISSUE THREAD

**Issue by CAHro** [kozi/contao-fullcalendar#15]
Lieber Kozi,

Ich habe ein Problem mit der Installation und ich hoffe du kannst mir weiterhelfen.
Ich benutze die Contao Version 3.5.28 und ich muss leider die Erweiterung ohne Composer installieren.
Ich habe schon herausgefunden, dass ich alles hier von Github via FTP (auch den src Ordner und die Events.php) in den Ordner system/mudules/"Fullcalendar" laden muss.
Das habe ich gemacht. Leider wird bei mir der Kalender und auch der Originalkalender von Contao nicht mehr angezeigt.

Hast du eine Ahnung was ich vergessen haben könnte? Muss ich noch irgendwas verknüpfen?
Ich bin mit dem Composer noch etwas lost.

Schon einmal tausend Dank für die Hilfe!

Alles Liebe
Caro

**Comment by kozi** [comment]
Das wird ohne Composer nicht funktionieren. Wenn dein Webhost die Voraussetzungen für Composer erfüllt solltest du das auf jeden Fall mal ausprobieren. Ist in Contao eigentlich fast genauso zu verwenden wie die Erweiterungsverwaltung.

Gruß Martin
