### ISSUE TITLE
events, die auf volle Stunden fallen, wie 18:00 oder 19:00 werden nicht richtig dargestellt

### ISSUE THREAD

**Issue by cmette** [kozi/contao-fullcalendar#2]
events, die auf volle Stunden fallen, wie z.B. 
18:00 News oder 
19:00 Concert
werden nur als 
18 News oder
19 Concert 
in der Monatsansicht dargestellt. Alle anderen events, die Minuten ungleich 0 führen, werden korrekt angezeigt.

**Comment by kozi** [comment]
Das ist das Standardverhalten von FullCalendar, http://fullcalendar.io/
Details: http://fullcalendar.io/docs/text/timeFormat/
