### ISSUE TITLE
Ganztages Termin werden nicht korrekt dargestellt.

### ISSUE THREAD

**Issue by ttnotet** [kozi/contao-fullcalendar#5]
Ganztages Termin im Quellkalender (Google) werden immer um einen Tage verlängert in Contao Kalender dargestellt. 

Homepage mit dem Kalender: 
![fullcalendar_contao](https://cloud.githubusercontent.com/assets/16062703/12930976/b8457bb8-cf7b-11e5-84ce-8c83fe985d85.PNG)

Darstellung beim Quellkalender:
![googlekalendar](https://cloud.githubusercontent.com/assets/16062703/12930956/8c9bb388-cf7b-11e5-8e6f-8bf7483c9655.PNG)

**Comment by kozi** [comment]
Ist der Kalender öffentlich? Würde das dann mal testen.

**Comment by ttnotet** [comment]
Ja der Kalender ist öffentlich.

**Comment by kozi** [comment]
Fixed in 0.6.7

**Comment by kozi** [comment]
Example: http://kozianka.de/fullcalendar.html

**Comment by ttnotet** [comment]
Danke, funktioniert super.
