### ISSUE TITLE
Seit v0.6.9: Failed to parse time string (-3_months) at position 2 (_)

### ISSUE THREAD

**Issue by ttnotet** [kozi/contao-fullcalendar#7]
Seit dem update auf 0.6.9. tritt beim synchronisieren von Events im Eventsmenü tritt der folgende Fehler auf:

Fatal error: Uncaught exception Exception with message DateTime::__construct(): Failed to parse time string (-3_months) at position 2 (_): Unexpected character thrown in composer/vendor/martin-kozianka/contao-fullcalendar/src/ContaoFullcalendar/CalendarSync.php on line 91

#0 composer/vendor/martin-kozianka/contao-fullcalendar/src/ContaoFullcalendar/CalendarSync.php(91): DateTime->__construct('-3_months')
#1 composer/vendor/martin-kozianka/contao-fullcalendar/src/ContaoFullcalendar/CalendarSync.php(33): ContaoFullcalendar\CalendarSync->updateCalendar(Object(Contao\CalendarModel))
#2 system/modules/core/classes/Backend.php(430): ContaoFullcalendar\CalendarSync->syncOneCal(Object(Contao\DC_Table))
#3 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('calendar')
#4 contao/main.php(20): Contao\BackendMain->run()
#5 {main}

**Comment by r00t65** [comment]
Version 0.6.10:
Fatal error: Uncaught exception Exception with message DateTime::__construct(): Failed to parse time string (-3_months) at position 2 (_): Unexpected character thrown in composer/vendor/martin-kozianka/contao-fullcalendar/src/ContaoFullcalendar/CalendarSync.php on line 91

#0 composer/vendor/martin-kozianka/contao-fullcalendar/src/ContaoFullcalendar/CalendarSync.php(91): DateTime->__construct('-3_months')
#1 composer/vendor/martin-kozianka/contao-fullcalendar/src/ContaoFullcalendar/CalendarSync.php(33): ContaoFullcalendar\CalendarSync->updateCalendar(Object(Contao\CalendarModel))
#2 system/modules/core/classes/Backend.php(430): ContaoFullcalendar\CalendarSync->syncOneCal(Object(Contao\DC_Table))
#3 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('calendar')
#4 contao/main.php(20): Contao\BackendMain->run()
#5 {main}
