### ISSUE TITLE
CalDav Sync?

### ISSUE THREAD

**Issue by tognit** [kozi/contao-fullcalendar#8]
könnte man die Synchronisation der Termin auch über CalDav ausführen?

**Comment by kozi** [comment]
CalDav ist doch WebDAV. Die Option lässt sich doch auswählen. Setze das auch in einem Projekt ein.
Eine Synchronisation (in beide Richtungen bietet die Erweiterung jedoch nicht.) 
Wenn etwas nicht klappt melden Sie sich einfach...

**Comment by tognit** [comment]
Habe es gerade getestet und es funktioniert! Super Sache!
Wäre es den machbar eine Synchronisation in beide Richtungen ein zu bauen?

**Comment by kozi** [comment]
@Synchronisation: Eher nicht. Ist einfach ein relativ großer Aufwand alle Optionen,die ein Termin haben kann, zu mappen. Der Kalender ist einfach mehr zur Anzeige gedacht.
