### ISSUE TITLE
not working with jQuery 3.x

### ISSUE THREAD

**Issue by Toccamonium** [kozi/contao-fullcalendar#9]
Hi,
actually we wanted to replace jQuery 2.x with the latest 3.x because we don't need support of old browsers. Problem is, you cool extension is not running with that version. Would be cool to fix this issue. 

Thanks Florian

**Comment by kozi** [comment]
**Could you please add some details.**
[`https://kozianka.de/fullcalendar/`](https://kozianka.de/fullcalendar/)  This version runs with jQuery 3.1.1 without problems.

**Comment by Toccamonium** [comment]
I got this error and the link in the console leads to this page https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Errors/Unexpected_type

![28-02-_2017_09-42-56](https://cloud.githubusercontent.com/assets/1674576/23398194/d69444a6-fd9b-11e6-9e3a-634969e64ba9.png)

Any idea what this could cause this?

**Comment by kozi** [comment]
No! Example?!

**Comment by Toccamonium** [comment]
I try to setup an demo login, because right now I just have a real login to see the calendar page.

**Comment by kozi** [comment]
Resolved?
